<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
// abstract class PluginComment extends BaseComment
// {
//  public function hasCommenter()
//  {
//    return ((string)$this['Commenter'] != null && (string)$this['Commenter'] != '');
//  }
// }