# <?php if(sfConfig::get('app_comments_commenter_class') == 'Commenter'): ?>
# Commenter:
#   columns:
#     username:
#       type:       string(255)
#     email:
#       type:       string(255)
#   relations:
#     Comment:
#       local:        id
#       type:         one
#       alias:        Comment
#       foreign:      user_id
#       foreignType:  one
#       foreignAlias: Commenter
# <?php endif ?>