---
Comment: 
  actAs:
    NestedSet:
      hasManyRoots: true
      rootColumnName: root_id
    Timestampable:
  columns:
    id:
      type: integer
      primary: true
      autoincrement: true
    subject:
      type:     string(255)
    body:
      type:     clob
    user_id:
      type:     integer